#!/bin/bash -x
#
# Startup script to install Chrome remote desktop and a desktop environment.
#
# See environmental variables at then end of the script for configuration
#

function install_desktop_env {
  PACKAGES="desktop-base xscreensaver dbus-x11"

  if [[ "$INSTALL_XFCE" != "yes" && "$INSTALL_CINNAMON" != "yes" && "$INSTALL_KDE" != "yes" && "$INSTALL_GNOME" != "yes" ]] ; then
    # neither XFCE nor any specified; install xfce
    INSTALL_XFCE=yes
  fi

  if [[ "$INSTALL_XFCE" = "yes" ]] ; then
    PACKAGES="$PACKAGES xfce4"
    echo "exec xfce4-session" > /etc/chrome-remote-desktop-session
    [[ "$INSTALL_FULL_DESKTOP" = "yes" ]] && \
      PACKAGES="$PACKAGES task-xfce-desktop"
  fi

  if [[ "$INSTALL_CINNAMON" = "yes" ]] ; then
    PACKAGES="$PACKAGES cinnamon-core"
    echo "exec cinnamon-session-cinnamon2d" > /etc/chrome-remote-desktop-session
    [[ "$INSTALL_FULL_DESKTOP" = "yes" ]] && \
      PACKAGES="$PACKAGES task-cinnamon-desktop"
  fi

  if [[ "$INSTALL_KDE" = "yes" ]] ; then
    PACKAGES="$PACKAGES kde-plasma-desktop"
    echo "exec /usr/bin/startkde" > /etc/chrome-remote-desktop-session
    [[ "$INSTALL_FULL_DESKTOP" = "yes" ]] && \
      PACKAGES="$PACKAGES task-kde-desktop"
  fi

  if [[ "$INSTALL_GNOME" = "yes" ]] ; then
    PACKAGES="$PACKAGES gnome-core"
    echo "exec gnome-session" > /etc/chrome-remote-desktop-session
    [[ "$INSTALL_FULL_DESKTOP" = "yes" ]] && \
      PACKAGES="$PACKAGES gnome"
  fi

  DEBIAN_FRONTEND=noninteractive \
    apt-get install --assume-yes $PACKAGES $EXTRA_PACKAGES

  systemctl disable lightdm.service
}

function download_and_install { # args URL FILENAME
  curl -L -o "$2" "$1"
  dpkg --install "$2"
  apt-get install --assume-yes --fix-broken
}

function is_installed {  # args PACKAGE_NAME
  dpkg-query --list "$1" | grep -q "^ii" 2>/dev/null
  return $?
}

# Configure the following environmental variables as required:
INSTALL_XFCE=yes
INSTALL_CINNAMON=yes
INSTALL_CHROME=yes
INSTALL_FULL_DESKTOP=yes
INSTALL_KDE=yes
INSTALL_GNOME=yes
INSTALL_TELEGRAM=yes
USER=tejas

# Any additional packages that should be installed on startup can be added here
EXTRA_PACKAGES="less bzip2 zip unzip tasksel wget"

apt-get update

# Adding non-root user for crdp ; password is "tejas"
useradd -m $USER && adduser $USER sudo && echo 'tejas:tejas' | chpasswd

# Install backports version of libgbm1 on Debian 9/stretch
[[ $(/usr/bin/lsb_release --codename --short) == "stretch" ]] && \
  apt-get install --assume-yes libgbm1/stretch-backports

! is_installed chrome-remote-desktop && \
  download_and_install \
    https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb \
    /tmp/chrome-remote-desktop_current_amd64.deb

install_desktop_env

[[ "$INSTALL_CHROME" = "yes" ]] && \
  ! is_installed google-chrome-stable && \
  download_and_install \
    https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    /tmp/google-chrome-stable_current_amd64.deb

[[ "$INSTALL_TELEGRAM" = "yes" ]] && \
  mkdir /home/$USER/Telegram && \
  wget -P /home/$USER/Telegram https://updates.tdesktop.com/tlinux/tsetup.2.9.14.beta.tar.xz && \
  tar xf /home/$USER/Telegram/tsetup*.tar.xz && rm /home/$USER/Telegram/tsetup*.tar.xz

echo "Chrome remote desktop installation completed"
